### ISSUE TITLE
Self-deployment failing

### ISSUE THREAD

**Issue by tpglitch** [DillonB07/Spotter#30]
I am trying to self-deploy this on Render but I cannot do it. Here are the deployment details:
![image](https://user-images.githubusercontent.com/123958345/235516233-75dcb31b-3f30-4ab9-905f-d2e150df92bd.png)
And here is the error:
![image](https://user-images.githubusercontent.com/123958345/235516345-1adb463a-50c3-4508-a4c1-fd8ee3286759.png)

**Comment by transcental** [comment]
Your run command is wrong.
Try using `cd frontend && npm run build && cd .. && gunicorn spotter.wsgi -b 0.0.0.0:3000` instead.
This will build the React frtontend and then start the Django server.
Also make sure you've included all the necessary environment variables or it won't work.

**Comment by tpglitch** [comment]
Webpack produced this error: `install 'webpack-cli' (yes/no): yes npm ERR! code ELIFECYCLE`
